### ISSUE TITLE
[QUESTION]: How to listen for `get_available_entities`

### ISSUE THREAD

**Issue by uvjim** [unfoldedcircle/integration-python-library#10]
This may a be a daft question... how would I listen to the `WsMessages.GET_AVAILABLE_ENTITIES` so that I can rebuild the list of available entities?  This message seems to be issued when the `Reload` link is clicked in the Web Configurator.

What I'm trying to achieve... As I iterate through building the integration I will be adding new entities (mainly buttons) and quite possibly removing them too.  I'm looking for a way to effectively be able to build those entities for both a new setup and for an existing setup.  In addition any buttons I remove should also be removed (or at the very list flagged for removal).

I hope this makes sense.

**Comment by zehnm** [comment]
The `get_available_entities` request is handled internally in the library and returns the entities which were put in `IntegrationAPI.available_entities`:
https://github.com/unfoldedcircle/integration-python-library/blob/v0.1.3/ucapi/api.py#L329-L336

Newly available entities can simply be added, as for example during setup flow: https://github.com/unfoldedcircle/integration-python-library/blob/v0.1.3/examples/setup_flow.py#L109

Note: the option to re-run the setup flow for an already configured integration is really high in our backlog. This will make things much simpler and convenient for the user. It's also a requirement for us to offer "multi-device" support for Android TV, Apple TV etc., so that an additional device can be added later.

**Comment by uvjim** [comment]
I saw that re: returning the `available_entities` value.  I wondered if there was to update that list based on the reload request.
Re-running the setup flow does indeed give me the updated list, but it also runs the whole setup flow again which includes searching the network for available devices to pre-populate the device that needs to be controlled.

**Comment by zehnm** [comment]
Maybe I don't fully understand your question.

You can add new entities to `IntegrationAPI.available_entities` whenever you like, not only during driver startup or setup-flow.
For example you could continuously scan the network for new devices with mDNS, SSDP, ... and then add new devices when they show up.
Or trigger a scan when the remote connects / asks for entity states.

Then when you go into the integration and click reload you will get the new entities without running setup. At the moment running setup again, will first delete the integration and all configured entities. Usually not that useful and annoying to loose your entities in the UI pages :-)
That's what the upcoming "re-configuration" will solve.

**Comment by zehnm** [comment]
The Home Assistant integration uses `get_entity_states` and `get_available_entities` to retrieve all entities from the HA server. It's not written in Python and uses direct WebSocket communication.

We could add a callback handler or something else to the Python integration library, if that helps. Suggestions are welcome :-)

**Comment by uvjim** [comment]
A callback on `get_available_entities` might be handy.  That would essentially allow the additional entities to be created at the point that the reload is asked for and any that aren't required anymore can be removed.

I'm just going through the setup flow at the moment making sure that all aspects are covered for me.  I've already separated the creating of entities so that I can call it whenever I need to.

I'm no Python expert but I am persistent and have a few Home Assistant integrations written, so not afraid of trying and get my hands dirty.

**Comment by uvjim** [comment]
I'll close this one down now. I've used the connect event and that seems to be doing the job. There's probably no need for a callback if this is working.
